const pdfParse = require('pdf-parse');

/**
 * PDFSummarizerService
 * Performs extractive summarization of PDF text content.
 * Uses TF-IDF-style keyword frequency scoring to select top sentences.
 * Detects document sections and estimates reading time.
 */
class PDFSummarizerService {
  async process(file) {
    let rawText = '';
    let pageCount = 1;
    const fileName = file ? file.originalname : 'document.pdf';

    if (file && file.buffer) {
      try {
        const parsed = await pdfParse(file.buffer);
        rawText = parsed.text || '';
        pageCount = parsed.numpages || 1;
      } catch (e) {
        console.warn('[PDFSummarizerService] Parse error:', e.message);
        rawText = '';
      }
    }

    const wordCount = rawText.split(/\s+/).filter(Boolean).length;
    const charCount = rawText.length;
    const avgWordsPerMin = 230; // average adult reading speed
    const readingMinutes = Math.ceil(wordCount / avgWordsPerMin);
    const sentenceCount = (rawText.match(/[.!?]+/g) || []).length;

    // Extract sentences
    const sentences = rawText
      .split(/(?<=[.!?])\s+/)
      .map(s => s.trim())
      .filter(s => s.length > 30 && s.length < 400);

    // Build word frequency map (stop-word filtered)
    const STOP_WORDS = new Set([
      'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
      'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
      'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
      'could', 'should', 'may', 'might', 'that', 'this', 'these', 'those',
      'it', 'its', 'as', 'not', 'no', 'so', 'if', 'then', 'than', 'also'
    ]);

    const wordFreq = {};
    rawText.toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')
      .split(/\s+/)
      .filter(w => w.length > 3 && !STOP_WORDS.has(w))
      .forEach(w => { wordFreq[w] = (wordFreq[w] || 0) + 1; });

    // Score sentences by sum of keyword frequencies
    const scoredSentences = sentences.map((s, idx) => {
      const words = s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/);
      const score = words.reduce((sum, w) => sum + (wordFreq[w] || 0), 0);
      return { text: s, score, idx };
    });

    // Top 8 sentences by score, then sort back by original order
    const topSentences = scoredSentences
      .sort((a, b) => b.score - a.score)
      .slice(0, 8)
      .sort((a, b) => a.idx - b.idx)
      .map(s => s.text);

    // Extract top keywords
    const topKeywords = Object.entries(wordFreq)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 15)
      .map(([word, freq]) => `${word} (${freq})`);

    // Detect section headers (lines that look like headings)
    const sections = rawText.split('\n')
      .map(l => l.trim())
      .filter(l =>
        l.length > 3 && l.length < 80 &&
        l === l.toUpperCase() &&
        /^[A-Z0-9\s\-:.,&]+$/.test(l)
      )
      .slice(0, 8);

    // Build summary report
    let summary = `╔══════════════════════════════════════════════════╗\n`;
    summary += `  azPDF AI EXECUTIVE SUMMARY REPORT\n`;
    summary += `╚══════════════════════════════════════════════════╝\n\n`;

    summary += `📄 DOCUMENT METADATA\n`;
    summary += `${'─'.repeat(48)}\n`;
    summary += `  File Name:       ${fileName}\n`;
    summary += `  Total Pages:     ${pageCount}\n`;
    summary += `  Word Count:      ${wordCount.toLocaleString()} words\n`;
    summary += `  Characters:      ${charCount.toLocaleString()}\n`;
    summary += `  Sentences:       ${sentenceCount.toLocaleString()}\n`;
    summary += `  Reading Time:    ~${readingMinutes} minute${readingMinutes !== 1 ? 's' : ''}\n`;
    summary += `  Analysis Date:   ${new Date().toLocaleString()}\n\n`;

    if (sections.length > 0) {
      summary += `📋 DETECTED SECTIONS\n`;
      summary += `${'─'.repeat(48)}\n`;
      sections.forEach((s, i) => { summary += `  ${i + 1}. ${s}\n`; });
      summary += '\n';
    }

    if (topKeywords.length > 0) {
      summary += `🔑 TOP KEYWORDS\n`;
      summary += `${'─'.repeat(48)}\n`;
      summary += `  ${topKeywords.join(' • ')}\n\n`;
    }

    summary += `📝 EXECUTIVE SUMMARY (Extractive AI)\n`;
    summary += `${'─'.repeat(48)}\n`;

    if (topSentences.length > 0) {
      topSentences.forEach((s, i) => {
        summary += `  [${i + 1}] ${s}\n\n`;
      });
    } else {
      summary += `  No sufficient text content found for summarization.\n`;
      summary += `  The document may be image-based, encrypted, or contain minimal text.\n\n`;
    }

    summary += `${'═'.repeat(50)}\n`;
    summary += `Generated by azPDF AI Summarizer Engine v2\n`;

    console.log(
      `[PDFSummarizerService] File=${fileName} | Words=${wordCount} | Sections=${sections.length} | TopSentences=${topSentences.length}`
    );

    return Buffer.from(summary, 'utf-8');
  }
}

module.exports = new PDFSummarizerService();
