const pdfParse = require('pdf-parse');

/**
 * PDFToMarkdownService
 * Converts PDF text to well-structured Markdown format.
 * Detects headings, lists, paragraphs, and code blocks.
 * Produces a clean, editor-ready .md file.
 */
class PDFToMarkdownService {
  async process(file) {
    let rawText = '';
    let pageCount = 1;
    const fileName = file ? file.originalname : 'document.pdf';

    if (file && file.buffer) {
      try {
        const parsed = await pdfParse(file.buffer);
        rawText = parsed.text || '';
        pageCount = parsed.numpages || 1;
      } catch (e) {
        console.warn('[PDFToMarkdownService] Parse error:', e.message);
      }
    }

    const wordCount = rawText.split(/\s+/).filter(Boolean).length;
    const lines = rawText.split('\n').map(l => l.trim()).filter(Boolean);

    let md = '';

    // YAML frontmatter
    md += `---\n`;
    md += `title: "${fileName.replace(/\.pdf$/i, '')}"\n`;
    md += `source: "${fileName}"\n`;
    md += `pages: ${pageCount}\n`;
    md += `words: ${wordCount}\n`;
    md += `converted: "${new Date().toISOString()}"\n`;
    md += `engine: "azPDF Markdown Engine v2"\n`;
    md += `---\n\n`;

    // Document title
    md += `# ${fileName.replace(/\.pdf$/i, '')}\n\n`;
    md += `> **Source:** \`${fileName}\` &nbsp;|&nbsp; **Pages:** ${pageCount} &nbsp;|&nbsp; **Words:** ${wordCount.toLocaleString()} &nbsp;|&nbsp; **Converted:** ${new Date().toLocaleDateString()}\n\n`;
    md += `---\n\n`;

    if (lines.length === 0) {
      md += `> ⚠️ No text content could be extracted from this PDF.\n`;
      md += `> The file may be image-based, encrypted, or contain only scanned content.\n`;
      md += `> Consider running OCR before converting to Markdown.\n\n`;
    } else {
      let sectionCount = 0;

      lines.forEach((line) => {
        // Heading 1: ALL CAPS, short
        if (line.length >= 3 && line.length <= 70 && line === line.toUpperCase() && /^[A-Z0-9\s\-:.,&']+$/.test(line)) {
          sectionCount++;
          md += `\n## ${this._titleCase(line)}\n\n`;

        // Heading 2: Ends with colon, or numbered section
        } else if (line.endsWith(':') && line.length < 80 && !line.includes('.')) {
          md += `\n### ${line.replace(/:$/, '')}\n\n`;

        // Numbered list item
        } else if (/^\d+[\.\)]\s+/.test(line)) {
          const text = line.replace(/^\d+[\.\)]\s+/, '').trim();
          md += `1. ${text}\n`;

        // Bullet list item (starts with dash, asterisk, or bullet char)
        } else if (/^[-•*▪→]\s+/.test(line)) {
          const text = line.replace(/^[-•*▪→]\s+/, '').trim();
          md += `- ${text}\n`;

        // Short line that might be a label/key-value
        } else if (line.includes(':') && line.length < 60 && !line.includes('.')) {
          const [key, ...rest] = line.split(':');
          md += `**${key.trim()}:** ${rest.join(':').trim()}\n\n`;

        // Regular paragraph
        } else {
          md += `${line}\n\n`;
        }
      });

      if (sectionCount === 0) {
        md += `\n---\n\n*Note: No structural headings detected. Content rendered as paragraphs.*\n`;
      }
    }

    md += `\n---\n\n`;
    md += `*Generated by [azPDF Markdown Engine v2](https://azpdf.app) — ${new Date().toLocaleString()}*\n`;

    console.log(
      `[PDFToMarkdownService] File=${fileName} | Pages=${pageCount} | Words=${wordCount} | Lines=${lines.length}`
    );

    return Buffer.from(md, 'utf-8');
  }

  _titleCase(str) {
    return str.toLowerCase().replace(/\b\w/g, c => c.toUpperCase());
  }
}

module.exports = new PDFToMarkdownService();
